service: serverless-demo

provider:
  name: aws
  runtime: nodejs8.10

functions:
  hello:
    handler: hello.handle
    events:
      - http:
          path: /
          method: get
  
  webhook:
    handler: webhook.handle
    events:
      - http:
          path: /webhook
          method: get

package:
  exclude:
    - README.md
