service: serverless-demo

provider:
  name: aws
  runtime: nodejs8.10
#  environment:
#    GITHUB_TOKEN: foo_bar


functions:
  hello:
    handler: hello.handle
    events:
      - http:
          path: /
          method: get
  
  webhook:
    handler: webhook.handle
    events:
      - http:
          path: /webhook
          method: post

package:
  exclude:
    - README.md
