service: serverless-demo

provider:
  name: aws
  runtime: dotnetcore2.1

package:
  artifact: bin/release/netcoreapp2.1/deploy-package.zip

functions:
  hello:
    handler: ServerlessDemo::ServerlessDemo.Handler::Hello
    events:
     - http:
         path: /
         method: get
